spring.application.name=spring_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/aistylist
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# OpenAI API 키 설정
openai.api.key={OPENAI_API_KEY}
# ?? ??? ??
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Fashion API 설정
fashion.api.url=http://localhost:8000

# 로깅 설정
logging.charset.console=UTF-8
logging.charset.file=UTF-8
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n